package tiles

import "fmt"

type TrackType int

const (
	SIMPLE_TRACK_TYPE TrackType = iota
	COMPLEX_CROSSING_TRACK_TYPE
	COMPLEX_COEXISTING_TRACK_TYPE
)

func GetTrackType(tile TrackTile) TrackType {
	switch tile {
	case STRAIGHT_TRACK_TILE:
		return SIMPLE_TRACK_TYPE
	case SHARP_CURVE_TRACK_TILE:
		return SIMPLE_TRACK_TYPE
	case GENTLE_CURVE_TRACK_TILE:
		return SIMPLE_TRACK_TYPE

	case BOW_AND_ARROW_TRACK_TILE:
		return COMPLEX_CROSSING_TRACK_TYPE
	case TWO_GENTLE_TRACK_TILE:
		return COMPLEX_CROSSING_TRACK_TYPE
	case TWO_STRAIGHT_TRACK_TILE:
		return COMPLEX_CROSSING_TRACK_TYPE

	case BASEBALL_TRACK_TILE:
		return COMPLEX_COEXISTING_TRACK_TYPE
	case LEFT_GENTLE_AND_SHARP_TRACK_TILE:
		return COMPLEX_COEXISTING_TRACK_TYPE
	case RIGHT_GENTLE_AND_SHARP_TRACK_TILE:
		return COMPLEX_COEXISTING_TRACK_TYPE
	case STRAIGHT_AND_SHARP_TRACK_TILE:
		return COMPLEX_COEXISTING_TRACK_TYPE
	}

	panic(fmt.Errorf("invalid track tile: %v", tile))
}
